name: HelloWorld
main: fi.silentnoodlemaster.helloword.HelloWorld
version: 1.0.0
api-version: 1.15
commands:
   reloadmessage:
      description: Realod the config file for HelloWorld.
      usage: /reloadhello
      permission: op
      permission-message: You don't have permission to do that